"""add_consent_records_and_subscriber_unsubscribe

Revision ID: 78c6e44fb9b9
Revises: eba48aa93b65
Create Date: 2026-04-05 21:32:32.912186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c6e44fb9b9'
down_revision = 'eba48aa93b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_records_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_consent_records_purpose'), ['purpose'], unique=False)

    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unsubscribe_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_subscribers_unsubscribe_token'), ['unsubscribe_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscribers_unsubscribe_token'))
        batch_op.drop_column('unsubscribed_at')
        batch_op.drop_column('unsubscribe_token')

    with op.batch_alter_table('consent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_records_purpose'))
        batch_op.drop_index(batch_op.f('ix_consent_records_email'))

    op.drop_table('consent_records')
    # ### end Alembic commands ###
